version: '2'
services:
  #db:
  #  image: postgres
  web:
    build: .
    container_name: node-nginx
    volumes:
      - ./apps:/usr/share/nginx/html
      - /home/pabagan/Datos/Cursos/Angular-10-projects:/usr/share/nginx/html/AngularJS
    #command: source hello.js
    ports:
      - "80:80"
      - "8080:8080"
      - "8000:8000"
      - "443:443"
      - "9000:9000"
      - "35729:35729"
    tty: true
    restart: always
  db:
    image: mongo:3.2
    container_name: mongoDB
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - ./db:/data/db
